name: Aula de CI Ceub - Com Testes

on: [push]

jobs:
  meu_trabalho:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Rodar Testes
        run: python test_main.py